aws_region          = "us-east-1"
project_id          = "cmtr-nizsrz3k"
vpc_name            = "cmtr-nizsrz3k-vpc"
public_subnet_name  = "cmtr-nizsrz3k-public-subnet-1"
security_group_name = "cmtr-nizsrz3k-sg"